### PR TITLE
Titles for all the created pages - resolves #166

### LINKED ISSUE #166: Titles on Page and Browser Tabs
Titles should be added to every page, in order to make it easier for users to know which tab to open if they have many opened tabs
This is done by adding `@section('title', {{ $product->title}})`

Titles for the following pages:
- [x]  Login & register pages
- [x]  Category page
- [x]  Profile related pages
- [x]  Posting Policy, Privacy, Refund, Terms pages
- [x]  Your Store page
- [x]  Ads and Wishlist related pages

### LINKED ISSUE #192: Each page should be identified by looking just at tabs on the browser

### PR DESCRIPTION
**Pull request by monnyy**
This resolves #166

### CODE REVIEW

**Comment by neqqash** [comment]
i took a look at it, when i go on the login page it does not display it in my tab. However, for the other elements (Home, categories) it does. I'm not sure if its just me, but if everyone else can take a look at it as well, we can merge this ASAP.

**Comment by kevcamel** [comment]
+839 lines of code changed 😂 @monnyy

**Comment by kevcamel** [comment]
You should start a fresh branch and make ur changes more atomic? Meaning that  you will only change the code you need to. If you feel that the indentation needs to be change on every single file in our repo, you should create an issue for it then fix only that issue in that PR.

**Comment by kevcamel** [comment]
@monnyy is this PR duplicate now? since you opened #206 ?

**Comment by monnyy** [comment]
This is because this version apparently crashes due to the indentation I made(which is not supposed to). Maybe in resolving the conflicts, something got messed up.

**Pull request closed without merging**
