### PR TITLE
Category page displays ads of looked up category and its children categories

### PR DESCRIPTION
**Pull request by BrandonBalala**
Solves issue #113

### CODE REVIEW

**Comment by classifiedz** [comment]
Checked this locally looks great! Maybe we could start uploading screen shots with PR’s of this sort as well?

**Comment by BrandonBalala** [comment]
@classifiedz I think that would be a great idea!  I recommend this, https://gyazo.com/ 
It's very easy to use and is pretty quick too , can capture images and even gifs.  We'll discuss this as a group on our next meeting

**Comment by neqqash** [comment]
i dont quite get the idea, but yes discussing this in our next meeting will be helpful :)

**Comment by monnyy** [comment]
Nice. Every category points to its subsequent subcategories.  So using the functions you implemented they have access to products, stored in the database.

**Pull request merged**
