### PR TITLE
Changes for fixing dropdown issue #23, navbar #22 and #21

### PR DESCRIPTION
**Pull request by Swallow666**
For #22, I delete 'my cart' because I don't think we need this function for our site. 

For #23 and #21, now in homepage for those not registered people, if they click 'sell stuff/your store/log in', page will jump to login page, and if they didn't registered, they can click on 'join us' to create an account in register page. 

I think it is important that there are "sell stuff/your store" button in home page also for not-registered people so they will know what this website actually is. And when they click these buttons, they may create an account. 

Well since this change is not lot, if it is ok for everyone, I will merge this.

### CODE REVIEW

**Comment by HanGao2333** [comment]
Great. I think it's ready for merging.

**Comment by laurie-y** [comment]
Next time, try and have separate commits for each issue that way it's easier to see what change is related to what issue.

**Comment by monnyy** [comment]
Smart decision on the way you thought of implementing the relation between the "sale/MyStore" and "login/register". This will minimize some redundancies.

**Comment by neqqash** [comment]
this seems perfect to me, letting our customers know what the purpose of the website is rather than forcing them to log in/register right away

**Comment by Swallow666** [comment]
Ok I will merge this one to master then, and next time I will separate commit for each issue. If there is anything need to be upgraded, just upgrade this version.

**Pull request merged**
