### PR TITLE
fix the footer layout issue and register password confirm enhancement

### PR DESCRIPTION
**Pull request by HanGao2333**

### CODE REVIEW

**Comment by Swallow666** [comment]
Greet stuff from Han for fixing footer layout issue, and I also wonder if we put all css file together is better.
Do we not need inline style at all?

**Comment by kevcamel** [comment]
@Swallow666 inline css is not encouraged. Seperate css file is always better, cleaner HTML and CSS means both files are easier to read and neat.
@HanGao2333 please reference the issue your solving in your commit, in this case you should mention that you are solving issue #32.
@HanGao2333 I really dislike absolute positioning, but if it works then lets go for it

**Comment by Swallow666** [comment]
@BrandonBalala @laurie-y  any idea about this?

**Comment by monnyy** [comment]
I switched to your branch and tried locally, but not sure your changes worked(the footer is not at the expected position)

**Comment by HanGao2333** [comment]
Guys maybe it's unstable and I can modified it like making it not absolute position.

**Comment by mohghalayini** [comment]
Can you guys remove me from the repository? i'm not even in your group.
Thanks

**Pull request closed without merging**
