### PR TITLE
Text changing to a better position #94

### PR DESCRIPTION
**Pull request by HanGao2333**

### CODE REVIEW

**Comment by laurie-y** [comment]
The changes look fine but try to avoid inline css and add it to the stylesheet instead.
Also, next time, reference the issues you're fixing in the actual commits rather than just the pull request.

**Review by laurie-y — COMMENTED** [review]
The changes look find but try and avoid inline css and make the changes to the stylesheet instead

**Comment by laurie-y** [comment]
Next time, reference the issues you're fixing in the actual commits rather than just the pull request.

**Comment by Swallow666** [comment]
Good fix for issue #94 ! I switch to your branch and test this locally, looks fine in register and login page but there is a overlap problem in reset page. I will merge this one and add commit to fix that and change in-line style to style-sheet.

**Pull request merged**
