### PR TITLE
Prices are now shown to the right instead of left, solves issue #174

### PR DESCRIPTION
**Pull request by neqqash**
thought it would look better if everything is aligned (date and price) to allow for simplicity.   solves issue #174

### CODE REVIEW

**Comment by BrandonBalala** [comment]
Indentation looks off, can you fix that please

**Comment by neqqash** [comment]
i hope its okay right now, did some quick changes on the online editor.

**Review by kevcamel — CHANGES_REQUESTED** [review]
@neqqash Can you fix the indentation on lines 42-56?

**Comment by neqqash** [comment]
let me know if the indentation is good now

**Comment by kevcamel** [comment]
Describe what the commit is regarding and reference an issue with ur commit.
looks good tho, ill close the PR once travis finishes

**Pull request merged**
