### PR TITLE
Creation of the individual ad page for user story #83 

### PR DESCRIPTION
**Pull request by laurie-y**
Home page cards are now linked to the individual ad page.
Page contains image, title, link(just # until merged) to seller profile, price, description, and date added.

Visual enhancements will follow along with prefered method of contact.

### CODE REVIEW

**Comment by kevcamel** [comment]
ad
looks really good! I don't think ill have time for review until Monday tho. Is anyone else up to grab this PR review ?

**Comment by BrandonBalala** [comment]
Can we maybe change how the date is being displayed, as in remove the "-" between Oct-14th and change the month to the full word

**Comment by laurie-y** [comment]
How's that?

**Comment by laurie-y** [comment]
oh wait i only removed the dash... whoops

**Review by monnyy — APPROVED** [review]
Well done on your part
Lines 1 - 23 of resources/views/viewAd.blade.php produces a format filled by pieces of information from the database.
Looks really good.

**Pull request merged**
